title: Generative AI for Technical Writing
description: Generative AI for Technical Writing
theme: just-the-docs

url: https://github.com/KinRap/GenerativeAIForTechWriters

aux_links:
  Template Repository: https://github.com/KinRap/GenerativeAIForTechWriters
